name: smk_losarangg
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  introduction_screen: ^1.0.8
  google_fonts: ^0.3.10
  carousel_pro: ^1.0.0
  load: ^0.1.5+1
  pull_to_refresh: ^1.6.1
  dropdown_formfield: ^0.1.1
  expandable: ^4.1.2
  timeago: ^2.0.26
  menu_button: ^0.1.1+1
  groovin_widgets: ^1.5.0+1
  stream_chat_flutter: ^0.1.35
  rounded_loading_button: ^1.0.0
  intl: ^0.16.1
  pigment: ^1.0.3
  flutter_speed_dial: ^1.2.5
  http: ^0.12.0+4
  fluttertoast: ^4.0.1
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  cached_network_image: ^2.0.0-rc
  photo_view: ^0.5.0
  toast: ^0.1.5
  ndialog: ^2.0.2+1
  shared_preferences: ^0.5.7
  firebase_messaging: ^6.0.13
  dio: ^3.0.9
  provider: ^4.1.2
  flushbar: ^1.10.4
  image_picker: ^0.6.7+4
  file_picker: ^1.13.0
  flutter_downloader: ^1.4.4
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.11
  ext_storage: ^1.0.3
  month_picker_dialog: ^0.3.2
  md2_tab_indicator: ^1.0.2
  flutter_datepicker_single: ^0.0.1+1
  expansion_tile_card: ^1.1.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/stikers/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
